run_model: dev
logger:
  level: debug
  file_config:
    file_name: ./logs/service.log
    enable: false
    maxsize: 100
    max_backups: 5
    max_age: 7
    compress: false
  enable_console: true
  enable_color: true

forwards:
  - src: 0.0.0.0:19999
    target: 192.168.30.38:15432
    network: tcp4